model_config:
  name: 'resnet'
  input_channels: 3
  learning_rate: 0.001
  manual_seed: 42
  block: BasicBlock
  h_dims: [3, 64, 64, 128, 256, 512] # 224, 112, 56, 28, 14, 7
  block_depth: [0, 2, 2, 2, 2] # resnet 18
  patch_size: 224
  dropout: 0.5
  num_classes: 100
  weight_decay: 0.01
  scheduler_gamma: 0.95
  EMA: None
  SWA: None

data_config:
  data_dir: "data/butterfly"
  batch_size: 16
  patch_size: 224
  num_workers: 4
  use_manual_split: False

trainer_config:
  accelerator: 'gpu'
  devices: 2  # 2 or [0, 1]
  max_epochs: 200
  precision: 16-mixed

log_config:
  name: "butterfly_resnet"
  save_dir: "logs/"
  check_dir: "logs/check"
  checkpoint: True
  model_summary: False
  
