model_config:
  name: 'gan'
  input_channels: 3
  learning_rate: 0.001
  manual_seed: 42
  h_dim:generator:    [512, 256, 128, 64, 32, 3]
  generator:up_index: [0, 1, 1, 1, 1, 1] # 1, 2, 4, 8, 16, 32
  h_dim:discriminator: [3, 128, 256, 512] # 32, 16, 8, 4
  generator:down_index: [0, 1, 1, 1] 
  patch_size: 32
  k: 1
  sampling_period: 1
  grid: 4
  weight_decay: 0.01
  scheduler_gamma: 0.95
  EMA: None
  SWA: None

data_config:
  data_dir: "data/flowers/train"
  batch_size: 16
  patch_size: 32
  num_workers: 4
  use_manual_split: True


trainer_config:
  accelerator: 'gpu'
  devices: 1  # 2 or [0, 1]
  max_epochs: 1000
  precision: 16-mixed

log_config:
  name: "flowers_gan"
  save_dir: "logs/"
  check_dir: "logs/check"
  checkpoint: True
  model_summary: False
  
