model_config:
  name: 'flowers_cnn'
  input_channels: 3
  learning_rate: 0.001
  manual_seed: 42
  h_dims: [3, 16, 32, 64, 128, 256] # 224, 112, 56, 28, 14, 7
  patch_size: 224
  dropout: 0.5
  num_classes: 5
  # latent_dim: 256
  # kld_weight: 0.002
data_config:
  data_dir: "data/flowers/train"
  batch_size: 16
  patch_size: 224
  num_workers: 4
  use_manual_split: True


trainer_config:
  accelerator: 'gpu'
  devices: 4  # 2 or [0, 1]
  max_epochs: 100

log_config:
  name: "flowers_cnn"
  save_dir: "logs/"
  check_dir: "logs/check"
  checkpoint_path: None
  model_summary: False
  
