model_config:
  name: 'vqvae'
  learning_rate: 0.001
  manual_seed: 42
  h_dims: [3, 16, 32, 64, 128, 256] # 224, 112, 56, 28, 14, 7
  patch_size: 224
  sampling_period: 10
  embed_dim: 256
  num_embed: 2048

data_config:
  data_dir: "data/flowers/train"
  batch_size: 16
  patch_size: 224
  num_workers: 4
  use_manual_split: True


trainer_config:
  accelerator: 'gpu'
  devices: [3]  # 2 or [0, 1]
  max_epochs: 500

log_config:
  name: "flower_vqvae"
  save_dir: "logs/"
  check_dir: "logs/check"
  checkpoint_path: None
  model_summary: True
  
